version: "3.8"

volumes:
    app_data:
        name: hds_app_data
    static_files:
        name: hds_static_files
    media_files:
        name: hds_media_files

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        image: hds:development
        container_name: hds_django
        command: /app/docker/start.sh server
        depends_on:
            - postgres
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:       
            - .:/app
            - static_files:/app/static:rw
            - media_files:/app/media:rw

    postgres:
        image: postgres:13.3-alpine
        hostname: hds-postgres
        container_name: hds_postgres
        volumes:
            - app_data:/var/lib/postgresql/data
        env_file:
            - .env
    
    
    
