# Generated by Django 4.2.3 on 2023-08-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_created_at_game_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.FloatField(default=1692193530.6377368),
        ),
        migrations.AlterField(
            model_name='game',
            name='finished_at',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
