# Generated by Django 4.2.3 on 2023-08-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_created_at_alter_game_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.FloatField(default=1692710372.9798768),
        ),
    ]
