# Generated by Django 4.2.3 on 2023-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_game_created_at_game_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='finished_at',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
